



module Emitter

open Ir

type EmittedFile = { Path: string; Content: string }


let emitComparisonOperator (operator: IrComparisonOperator) : string =
    match operator with
        | IrLessThan -> "<"
        | IrLessThanOrEqual -> "<="
        | IrGreaterThan -> ">"
        | IrGreaterThanOrEqual -> ">="
        | IrEquals -> "="
        | operator -> failwith $"Unsupported Operator ({operator})"



let emitInstruction (objective: string) (nameSpace: string) (instruction: IrInstruction) : string = 
    match instruction with
        | IrSetConstant (destination, value) -> 
            $"scoreboard players set {destination} {objective} {value}"
        | IrCopy (destination, source) -> 
            $"scoreboard players operation {destination} {objective} = {source} {objective}"
        | IrAdd (destination, source) -> 
            $"scoreboard players operation {destination} {objective} += {source} {objective}"
        | IrSubtract (destination, source) -> 
            $"scoreboard players operation {destination} {objective} -= {source} {objective}"
        | IrMultiply (destination, source) -> 
            $"scoreboard players operation {destination} {objective} *= {source} {objective}"
        | IrDivide (destination, source) -> 
            $"scoreboard players operation {destination} {objective} /= {source} {objective}"
        | IrModulo (destination, source) -> 
            $"scoreboard players operation {destination} {objective} %%= {source} {objective}"

        | IrStorageSet (path, value) -> 
            failwith "Storage Set Not Implemented Yet"
        | IrStorageGet (destination, path) ->
            failwith "Storage Get Not Implemented Yet"

        | IrCall functionName -> 
            $"function {nameSpace}:{functionName}"
        | IrConditionalCall (valueA, IrNotEquals, valueB, functionName) ->
            $"execute unless score {valueA} {objective} = {valueB} {objective} run function {nameSpace}:{functionName}"
        | IrConditionalCall (valueA, operator, valueB, functionName) -> 
            let operatorString = emitComparisonOperator operator
            $"execute if score {valueA} {objective} {operatorString} {valueB} {objective} run function {nameSpace}:{functionName}"
        | IrMacroCall (functionName, storageArgumentPath) -> 
            failwith "Macro Calls Not Implemented Yet"

        | IrRawCommand command -> command

let emitFunction (objective: string) (nameSpace: string) (func: IrFunction) : EmittedFile =
    let lines =
        func.Instructions
        |> List.map (emitInstruction objective nameSpace)

    let content = String.concat "\n" lines

    { Path = $"data/{nameSpace}/function/{func.Name}.mcfunction"; Content = content }

let emitProgram (program: IrProgram) (nameSpace: string) (objective: string) : EmittedFile list =
    let functionFiles =
        program.Functions
        |> List.map (emitFunction objective nameSpace)

    let packMetaFile = 
        { Path = "pack.mcmeta"; Content = $"{{ \"pack\": {{ \"pack_format\": 61, \"description\": \"{nameSpace} (Generated by mcf#)\" }}}}" }

    let loadTagFile = 
        match program.Functions |> List.tryFind (fun func -> func.Name = "load") with
            | Some _ ->
                Some({ Path = $"data/minecraft/tags/function/load.json"; Content = $"{{ \"values\": [\"{nameSpace}:load\"] }}" })
            | None -> None
        
         

    let tickTagFile = 
        match program.Functions |> List.tryFind (fun func -> func.Name = "tick") with
            | Some _ ->
                Some({ Path = $"data/minecraft/tags/function/tick.json"; Content = $"{{ \"values\": [\"{nameSpace}:tick\"] }}" })
            | None -> None

    functionFiles @ [packMetaFile] @ Option.toList loadTagFile @ Option.toList tickTagFile


    
    
